### ISSUE TITLE
ERROR: Failed building wheel for unknown

### ISSUE THREAD

**Issue by ghost** [sashs/filebytes#17]
I have some error when install from pip on Ubuntu 16.04 (Backbox Linux).
The python version is "Python 3.5.2 (default, Nov 12 2018, 13:43:14)".

```
root[~] >> pip install filebytes
Collecting filebytes
  Downloading https://files.pythonhosted.org/packages/0b/3a/9fc0c62bd74583137a8bbc3c8020d6a8234b9cf8bc1e99fe929688b19093/filebytes-0.9.20.tar.gz
  WARNING: Generating metadata for package filebytes produced metadata for project name unknown. Fix your #egg=filebytes fragments.
Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/0b/3a/9fc0c62bd74583137a8bbc3c8020d6a8234b9cf8bc1e99fe929688b19093/filebytes-0.9.20.tar.gz#sha256=6c33986ca048e49cf1a5e2f167af9f02c7f866576b3b91a8a9124d32e57f935d in /usr/local/lib/python3.5/dist-packages/UNKNOWN-0.9.20-py3.5.egg
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/5e/69/2b/08660fcb6cd841d60ff8980be781f40ee15ff014c5aaaace29
  Building wheel for unknown (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.5 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-13mrh900/unknown/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-x8zwjl3s --python-tag cp35:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-13mrh900/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for unknown
  Running setup.py clean for unknown
  ERROR: Complete output from command /usr/bin/python3.5 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-13mrh900/unknown/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-13mrh900/unknown/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
```

**Comment by sashs** [comment]
Hi,

the problem is your very old python version. filebytes uses a feature of setuptools that has been introduced in December 2016. https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files
