### ISSUE TITLE
Fails on large PE

### ISSUE THREAD

**Issue by hugsy** [sashs/filebytes#5]
Hi,

I've been manipulating "large" PE files (i.e. more than 5MB) and `filebytes` fails when trying to parse the structure. 

For example with `ntoskrnl.exe`:
```bash
# ls -lah /vagrant/ntoskrnl.exe
-rw-r--r-- 1 root root 5.5M Jan 11 09:50 /vagrant/ntoskrnl.exe
#  python3
Python 3.6.4 (default, Dec 19 2017, 14:09:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from filebytes.pe import *
>>> p = PE('/vagrant/ntoskrnl.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/filebytes/pe.py", line 432, in __init__
    self.__dataDirectory = self._parseDataDirectory(self._bytes, self.sections, self.imageNtHeaders)
  File "/usr/local/lib/python3.6/dist-packages/filebytes/pe.py", line 535, in _parseDataDirectory
    import_data_directory_data = self._parseDataDirectoryImport(import_data_directory, import_section)
  File "/usr/local/lib/python3.6/dist-packages/filebytes/pe.py", line 592, in _parseDataDirectoryImport
    import_address_table =  self.__parseThunks(import_descriptor.FirstThunk, importSection)
  File "/usr/local/lib/python3.6/dist-packages/filebytes/pe.py", line 651, in __parseThunks
    self.__parseThunkData(thunkData, importSection)
  File "/usr/local/lib/python3.6/dist-packages/filebytes/pe.py", line 662, in __parseThunkData
    ibn = IMAGE_IMPORT_BY_NAME.from_buffer(importSection.raw, offset)
ValueError: Buffer size too small (8192 instead of at least 3093560 bytes)
```

Any idea?

Thanks!

**Comment by sashs** [comment]
Hey,

I assume something is parsed in a wrong way. I am going to check that tomorrow. 
Is that a 32 or 64bit PE file?

cheers

**Comment by hugsy** [comment]
I cannot send you the initial PE on which I found it, but it was a x64 PE.
The listing from above was taken with `ntoskrnl.exe` from Windows 10 RS2 x64.

**Comment by sashs** [comment]
Ok, Thx.

**Comment by sashs** [comment]
Hi @hugsy,

apologize, the delay. could you do me a favor and check this behavior with the current version? I cannot reproduce this issue with a current win10 ntoskrnl.exe.

**Comment by hugsy** [comment]
Hey,

Not sure what changed (maybe it was my setup fault) but I cannot repro. So let's close this.

Cheers
